site_name: Adventures in Linux
theme: readthedocs
site_author: Riley Albiston

#site_url: https://example.com/foo/

nav:
    - Home: 'index.md'
    - Apache Airflow Install: 'apache-airflow-install.md'
    - Apache NiFi Install: 'apache-nifi-install.md'
    - Jellyfin Install: 'jellyfin-install.md'
    - Nextcloud Install: 'nextcloud-install.md'
    - Setup LAMP Stack with Wordpress: 'setup-lamp-stack-with-wordpress.md'
    - Setup Nginx, PostgrSQL and Flask App: 'setup-nginx-postesql-flask-app-on-linux.md'
    - Setup Software Installation: 'setup-software-install.md'
    - Nginx Install and Inital Setup: 'nginx-install-and-setup.md'
    - Nginx Setup Subdomains: 'nginx-setup-subdomains.md'
    - Nginx Bash Script: 'nginx-bash-script.md'
    - PostgrSQL Install and Setup:  'postgres-install-and-setup.md'
    - PostgreSQL Setup: 'setup-postgres.md'
    - SQL Server Install and Setup: 'sql-server-install-and-setup.md'
    - SSH install: 'setup-ssh.md'
    - Misc Linux Stuff: 'misc-linux.md'



#repo_url: https://github.com/rileyalbiston/


















